# -*- coding: utf-8 -*-
"""imageClassificator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8LAS0GfEZx7wsQAOEcNBC8JISM1eX_j
"""

from google.colab import files
uploaded = files.upload()

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input, decode_predictions
import numpy as np
import matplotlib.pyplot as plt

# Carregar o Modelo Pré-Treinado MobileNetV2 com ImageNet
model = MobileNetV2(weights='imagenet')

# Carregar e Pré-processar a Imagem
img_path = 'person.jpg'  # Substitua com o caminho correto
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  # Adiciona a dimensão do batch
img_array = preprocess_input(img_array)  # Pré-processamento do MobileNetV2

# Fazer a Previsão
predictions = model.predict(img_array)
decoded_predictions = decode_predictions(predictions, top=3)[0]  # As top 3 classes previstas

# Exibir as previsões
for i, (imagenet_id, label, score) in enumerate(decoded_predictions):
    print(f"{i+1}: {label} ({score:.2f})")

# Visualizar a Imagem
plt.imshow(img)
plt.axis('off')
plt.show()